// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHR59qKN9jSNI6tRxV_LOt_RG1t3dytA',
    appId: '1:156255050730:web:38456607a648d528ea3093',
    messagingSenderId: '156255050730',
    projectId: 'lubok-antu-rescuenet',
    authDomain: 'lubok-antu-rescuenet.firebaseapp.com',
    storageBucket: 'lubok-antu-rescuenet.firebasestorage.app',
    measurementId: 'G-JXEP6XED9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9TIWbrJ-Pvg9ASav99N-r3hkMcRfDyM',
    appId: '1:156255050730:android:e90e9c14d616173eea3093',
    messagingSenderId: '156255050730',
    projectId: 'lubok-antu-rescuenet',
    storageBucket: 'lubok-antu-rescuenet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJI_gLZ0RjhxRb_IMtLY6kWkBtX_vyDQ',
    appId: '1:156255050730:ios:726b195ac1b227abea3093',
    messagingSenderId: '156255050730',
    projectId: 'lubok-antu-rescuenet',
    storageBucket: 'lubok-antu-rescuenet.firebasestorage.app',
    iosBundleId: 'com.example.lar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArJI_gLZ0RjhxRb_IMtLY6kWkBtX_vyDQ',
    appId: '1:156255050730:ios:726b195ac1b227abea3093',
    messagingSenderId: '156255050730',
    projectId: 'lubok-antu-rescuenet',
    storageBucket: 'lubok-antu-rescuenet.firebasestorage.app',
    iosBundleId: 'com.example.lar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJHR59qKN9jSNI6tRxV_LOt_RG1t3dytA',
    appId: '1:156255050730:web:1ed010b112f078a1ea3093',
    messagingSenderId: '156255050730',
    projectId: 'lubok-antu-rescuenet',
    authDomain: 'lubok-antu-rescuenet.firebaseapp.com',
    storageBucket: 'lubok-antu-rescuenet.firebasestorage.app',
    measurementId: 'G-3ZY2D94V42',
  );
}
